version: '3.8'

services:
  market_simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - market_net

  broker:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    depends_on:
      - market_simulator
    networks:
      - market_net

networks:
  market_net:
    driver: bridge
